services:
  postgres:
    network_mode: host

  mosquitto:
    network_mode: host

  backend:
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
    environment:
      - DB_HOST=127.0.0.1
      - MQTT_URL=mqtt://127.0.0.1:1883

  frontend:
    network_mode: host

  nginx:
    network_mode: host
